name: building blocks
favicon: null
layout_spectrum: 0.538988095941022
typography_spectrum: 0.08717284863814712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7921329457312822
  lightness: 0.6069585911463946
  saturation: 0.9972507988568395
  rhythmicContrast: 0.7021144817117602
purpose: []
